[package]
name = "rust_serialization_benchmark"
version = "0.1.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abomonation = { version = "0.7", optional = true }
abomonation_derive = { version = "0.5", optional = true }
bincode = { version = "1.3", optional = true }
borsh = { version = "0.9", optional = true }
bytecheck = { version = "0.6", optional = true }
capnp = { version = "0.14", optional = true }
criterion = "0.3"
flatbuffers = { version = "2.0", optional = true }
libflate = "1.0"
nachricht-serde = { version = "0.3", optional = true }
postcard = { version = "0.7", features = ["alloc"], optional = true }
prost = { version = "0.7", optional = true }
rand = "0.8"
rkyv = { version = "0.7.0", features = ["validation"], optional = true }
rmp-serde = { version = "0.15", optional = true }
ron = { version = "0.6", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_cbor = { version = "0.11", optional = true }
serde_json = { version = "1.0", optional = true }
speedy = { version = "0.7", optional = true }
alkahest = { version = "0.1.4", optional = true, features = ["derive", "nightly"] } # "nightly" feature won't be required starting with rustc 1.55
bytemuck = { version = "1.0" }

[features]
default = [
    "abomonation",
    "abomonation_derive",
    "bincode",
    "borsh",
    "bytecheck",
    "capnp",
    "flatbuffers",
    "nachricht-serde",
    "postcard",
    "prost",
    "rkyv",
    "rmp-serde",
    "ron",
    "serde",
    "serde_cbor",
    "serde_json",
    "speedy",
    "alkahest"
]

[dev-dependencies]
rand_pcg = "0.3"

[build-dependencies]
capnp = "0.14"
capnpc = "0.14"
prost-build = { version = "0.7" }

[[bench]]
name = "bench"
harness = false

# Uncomment this to profile
# [profile.bench]
# debug = true
