[package]
name = "rust_serialization_benchmark"
version = "0.1.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3"
criterion = "0.3"
flatbuffers = "0.7"
rand = "0.8"
rkyv = "0.4"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rand_pcg = "0.3"

[[bench]]
name = "minecraft_savedata"
harness = false
